import './Footer.css.proxy.js';
/* src/components/common/Footer.svelte generated by Svelte v3.29.4 */
import {
	SvelteComponent,
	attr,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from "../../../web_modules/svelte/internal.js";

function create_fragment(ctx) {
	let footer;

	return {
		c() {
			footer = element("footer");
			footer.innerHTML = `<p class="footer__copyright svelte-dbh34q"><small>Copyright (c) NaoNao All Rights Reserved.</small></p>`;
			attr(footer, "class", "footer svelte-dbh34q");
		},
		m(target, anchor) {
			insert(target, footer, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(footer);
		}
	};
}

function instance($$self) {
	"use strict";
	return [];
}

class Footer extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default Footer;