import './Header.css.proxy.js';
/* src/components/common/Header.svelte generated by Svelte v3.31.0 */
import {
	SvelteComponent,
	action_destroyer,
	append,
	attr,
	detach,
	element,
	init,
	insert,
	noop,
	run_all,
	safe_not_equal,
	space
} from "../../../web_modules/svelte/internal.js";

import Router, { link } from "../../../web_modules/svelte-spa-router.js";

function create_fragment(ctx) {
	let header;
	let nav;
	let div2;
	let div0;
	let h1;
	let a0;
	let link_action;
	let t1;
	let div1;
	let ul;
	let li0;
	let a1;
	let link_action_1;
	let t4;
	let li1;
	let a2;
	let link_action_2;
	let t7;
	let li2;
	let mounted;
	let dispose;

	return {
		c() {
			header = element("header");
			nav = element("nav");
			div2 = element("div");
			div0 = element("div");
			h1 = element("h1");
			a0 = element("a");
			a0.textContent = "NaoNao";
			t1 = space();
			div1 = element("div");
			ul = element("ul");
			li0 = element("li");
			a1 = element("a");

			a1.innerHTML = `<span data-uk-icon="home" aria-hidden="true"></span> 
                            <span class="header-nav__letter-gap svelte-bfr8vd"></span> Home`;

			t4 = space();
			li1 = element("li");
			a2 = element("a");

			a2.innerHTML = `<span data-uk-icon="user" aria-hidden="true"></span> 
                            <span class="header-nav__letter-gap svelte-bfr8vd"></span> Profile`;

			t7 = space();
			li2 = element("li");

			li2.innerHTML = `<a href="https://n06ar.hatenablog.com" class="header-nav__link svelte-bfr8vd"><span data-uk-icon="bookmark" aria-hidden="true"></span> 
                            <span class="header-nav__letter-gap svelte-bfr8vd"></span> Blog <span class="header-nav__letter-gap svelte-bfr8vd"></span><span data-uk-icon="icon: push;" aria-hidden="true"></span></a>`;

			attr(a0, "href", "/");
			attr(a0, "class", "header-title__text svelte-bfr8vd");
			attr(h1, "class", "header__title uk-logo svelte-bfr8vd");
			attr(div0, "class", "uk-navbar-left");
			attr(a1, "href", "/");
			attr(a1, "class", "header-nav__link svelte-bfr8vd");
			attr(a2, "href", "/profile");
			attr(a2, "class", "header-nav__link svelte-bfr8vd");
			attr(ul, "class", "header__nav uk-navbar-nav");
			attr(div1, "class", "uk-navbar-right");
			attr(div2, "class", "header svelte-bfr8vd");
			attr(nav, "class", "uk-navbar-container uk-margin");
			attr(nav, "data-uk-navbar", "");
			attr(header, "data-uk-sticky", "sel-target: .uk-navbar-container; cls-active: uk-navbar-sticky");
		},
		m(target, anchor) {
			insert(target, header, anchor);
			append(header, nav);
			append(nav, div2);
			append(div2, div0);
			append(div0, h1);
			append(h1, a0);
			append(div2, t1);
			append(div2, div1);
			append(div1, ul);
			append(ul, li0);
			append(li0, a1);
			append(ul, t4);
			append(ul, li1);
			append(li1, a2);
			append(ul, t7);
			append(ul, li2);

			if (!mounted) {
				dispose = [
					action_destroyer(link_action = link.call(null, a0)),
					action_destroyer(link_action_1 = link.call(null, a1)),
					action_destroyer(link_action_2 = link.call(null, a2))
				];

				mounted = true;
			}
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(header);
			mounted = false;
			run_all(dispose);
		}
	};
}

class Header extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Header;