import{SvelteComponent as S,append as t,attr as d,detach as P,element as e,init as x,insert as C,noop as w,safe_not_equal as R,space as n}from"../../../_snowpack/pkg/svelte/internal.js";function D(f){let i,r,_,s,o,a,l,c,H,p,u,v,A,m,L,q,y,g,M,b,T,h;return{c(){i=e("section"),r=e("h2"),r.innerHTML='<span data-uk-icon="icon: user; ratio: 1.5" aria-hidden="true"></span> Profile',_=n(),s=e("section"),o=e("div"),o.innerHTML='<img class="profile__icon svelte-11o1hlq" src="https://avatars0.githubusercontent.com/u/56122838?s=460&amp;u=223fe136c3c00e8150fe1967439ae3e7b5ca87d5&amp;v=4" alt="Nobuhito Arai&#39;s icon"/>',a=n(),l=e("div"),c=e("dl"),c.innerHTML="<dt>Name</dt><dd>Nobuhito Arai</dd>",H=n(),p=e("dl"),u=e("dt"),u.textContent="Age",v=e("dd"),v.textContent=`${f[0](1991,4,12)} years old`,A=n(),m=e("dl"),m.innerHTML=`<dt>Academic Background</dt><dd><ul><li>\u6D66\u548C\u5B9F\u696D\u5B66\u5712\u9AD8\u7B49\u5B66\u6821 \u666E\u901A\u79D1</li> 
                        <li>\u62D3\u6B96\u5927\u5B66 \u5DE5\u5B66\u90E8 \u60C5\u5831\u5DE5\u5B66\u79D1</li> 
                        <li>\u62D3\u6B96\u5927\u5B66\u5927\u5B66\u9662 \u5DE5\u5B66\u7814\u7A76\u79D1 \u60C5\u5831\u30C7\u30B6\u30A4\u30F3\u5DE5\u5B66\u5C02\u653B</li></ul></dd>`,L=n(),q=e("dl"),q.innerHTML=`<dt>Programming Languages</dt><dd><ul class="profile-content__list -two-rows svelte-11o1hlq"><li class="profile-content-list__item svelte-11o1hlq">Java</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">PHP</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">Objective-C</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">Swift</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">Kotlin</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">JavaScript</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">HTML</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">CSS</li></ul></dd>`,y=n(),g=e("dl"),g.innerHTML=`<dt>Frameworks</dt><dd><ul class="profile-content__list -two-rows svelte-11o1hlq"><li class="profile-content-list__item svelte-11o1hlq">Spring</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">CakePHP</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">Laravel</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">Vue.js</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">React</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">Svelte</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">Scss</li></ul></dd>`,M=n(),b=e("dl"),b.innerHTML=`<dt>Accounts</dt><dd><ul><li><a class="profile-account__link svelte-11o1hlq" href="https://twitter.com/N06Ar"><span class="profile-account__icon -twitter svelte-11o1hlq" data-uk-icon="twitter" aria-label="Twitter"></span> @N06AR</a></li> 
                        <li><a class="profile-account__link svelte-11o1hlq" href="https://github.com/n06Ar"><span data-uk-icon="github" aria-label="GitHub"></span> @N06AR</a></li> 
                        <li><a class="profile-account__link svelte-11o1hlq" href="https://qiita.com/N06AR"><span data-uk-icon="file-text" aria-label="Qiita"></span> @N06AR</a></li> 
                        <li><a class="profile-account__link svelte-11o1hlq" href="https://n06ar.hatenablog.com/"><span data-uk-icon="bookmark" aria-label="Hatena Blog"></span> @N06AR</a></li></ul></dd>`,T=n(),h=e("section"),h.innerHTML='<h3 class="profile-content__title">Working History</h3>',d(o,"class","profile-body__content -icon svelte-11o1hlq"),d(l,"class","profile-body__content -text svelte-11o1hlq"),d(h,"class","profile-body__content -history svelte-11o1hlq"),d(s,"class","profile__body svelte-11o1hlq"),d(i,"class","profile svelte-11o1hlq")},m(k,N){C(k,i,N),t(i,r),t(i,_),t(i,s),t(s,o),t(s,a),t(s,l),t(l,c),t(l,H),t(l,p),t(p,u),t(p,v),t(l,A),t(l,m),t(l,L),t(l,q),t(l,y),t(l,g),t(l,M),t(l,b),t(s,T),t(s,h)},p:w,i:w,o:w,d(k){k&&P(i)}}}function F(f){"use strict";const i=(r,_,s)=>{const o=new Date(r,_-1,s),a=new Date,l=new Date(a.getFullYear(),o.getMonth(),o.getDate()),c=a.getFullYear()-o.getFullYear();return a<l?c-1:c};return[i]}class Y extends S{constructor(i){super();x(this,i,F,D,R,{})}}export default Y;
