import './Profile.css.proxy.js';
/* src/components/pages/Profile.svelte generated by Svelte v3.29.4 */
import {
	SvelteComponent,
	append,
	attr,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	space
} from "../../../web_modules/svelte/internal.js";

function create_fragment(ctx) {
	let section2;
	let h2;
	let t1;
	let section1;
	let div0;
	let t2;
	let div1;
	let dl0;
	let t5;
	let dl1;
	let dt1;
	let dd1;
	let t9;
	let dl2;
	let t16;
	let dl3;
	let t33;
	let dl4;
	let t48;
	let dl5;
	let t57;
	let section0;

	return {
		c() {
			section2 = element("section");
			h2 = element("h2");
			h2.innerHTML = `<span data-uk-icon="icon: user; ratio: 1.5" aria-hidden="true"></span> Profile`;
			t1 = space();
			section1 = element("section");
			div0 = element("div");
			div0.innerHTML = `<img class="profile__icon svelte-11o1hlq" src="https://avatars0.githubusercontent.com/u/56122838?s=460&amp;u=223fe136c3c00e8150fe1967439ae3e7b5ca87d5&amp;v=4" alt="Nobuhito Arai&#39;s icon"/>`;
			t2 = space();
			div1 = element("div");
			dl0 = element("dl");
			dl0.innerHTML = `<dt>Name</dt><dd>Nobuhito Arai</dd>`;
			t5 = space();
			dl1 = element("dl");
			dt1 = element("dt");
			dt1.textContent = "Age";
			dd1 = element("dd");
			dd1.textContent = `${/*getAge*/ ctx[0](1991, 4, 12)} years old`;
			t9 = space();
			dl2 = element("dl");

			dl2.innerHTML = `<dt>Academic Background</dt><dd><ul><li>浦和実業学園高等学校 普通科</li> 
                        <li>拓殖大学 工学部 情報工学科</li> 
                        <li>拓殖大学大学院 工学研究科 情報デザイン工学専攻</li></ul></dd>`;

			t16 = space();
			dl3 = element("dl");

			dl3.innerHTML = `<dt>Programming Languages</dt><dd><ul class="profile-content__list -two-rows svelte-11o1hlq"><li class="profile-content-list__item svelte-11o1hlq">Java</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">PHP</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">Objective-C</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">Swift</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">Kotlin</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">JavaScript</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">HTML</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">CSS</li></ul></dd>`;

			t33 = space();
			dl4 = element("dl");

			dl4.innerHTML = `<dt>Frameworks</dt><dd><ul class="profile-content__list -two-rows svelte-11o1hlq"><li class="profile-content-list__item svelte-11o1hlq">Spring</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">CakePHP</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">Laravel</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">Vue.js</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">React</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">Svelte</li> 
                        <li class="profile-content-list__item svelte-11o1hlq">Scss</li></ul></dd>`;

			t48 = space();
			dl5 = element("dl");

			dl5.innerHTML = `<dt>Accounts</dt><dd><ul><li><a class="profile-account__link svelte-11o1hlq" href="https://twitter.com/N06Ar"><span class="profile-account__icon -twitter svelte-11o1hlq" data-uk-icon="twitter" aria-label="Twitter"></span> @N06AR</a></li> 
                        <li><a class="profile-account__link svelte-11o1hlq" href="https://github.com/n06Ar"><span data-uk-icon="github" aria-label="GitHub"></span> @N06AR</a></li> 
                        <li><a class="profile-account__link svelte-11o1hlq" href="https://qiita.com/N06AR"><span data-uk-icon="file-text" aria-label="Qiita"></span> @N06AR</a></li> 
                        <li><a class="profile-account__link svelte-11o1hlq" href="https://n06ar.hatenablog.com/"><span data-uk-icon="bookmark" aria-label="Hatena Blog"></span> @N06AR</a></li></ul></dd>`;

			t57 = space();
			section0 = element("section");
			section0.innerHTML = `<h3 class="profile-content__title">Working History</h3>`;
			attr(div0, "class", "profile-body__content -icon svelte-11o1hlq");
			attr(div1, "class", "profile-body__content -text svelte-11o1hlq");
			attr(section0, "class", "profile-body__content -history svelte-11o1hlq");
			attr(section1, "class", "profile__body svelte-11o1hlq");
			attr(section2, "class", "profile svelte-11o1hlq");
		},
		m(target, anchor) {
			insert(target, section2, anchor);
			append(section2, h2);
			append(section2, t1);
			append(section2, section1);
			append(section1, div0);
			append(section1, t2);
			append(section1, div1);
			append(div1, dl0);
			append(div1, t5);
			append(div1, dl1);
			append(dl1, dt1);
			append(dl1, dd1);
			append(div1, t9);
			append(div1, dl2);
			append(div1, t16);
			append(div1, dl3);
			append(div1, t33);
			append(div1, dl4);
			append(div1, t48);
			append(div1, dl5);
			append(section1, t57);
			append(section1, section0);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(section2);
		}
	};
}

function instance($$self) {
	"use strict";

	const getAge = (year, month, day) => {
		const birthday = new Date(year, month - 1, day);
		const today = new Date();
		const thisYearBirthday = new Date(today.getFullYear(), birthday.getMonth(), birthday.getDate());
		const age = today.getFullYear() - birthday.getFullYear();

		//今年の誕生日を迎えていなければage-1を返す
		return today < thisYearBirthday ? age - 1 : age;
	};

	return [getAge];
}

class Profile extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default Profile;