import './App.css.proxy.js';
/* src/components/App.svelte generated by Svelte v3.31.0 */
import {
	SvelteComponent,
	attr,
	create_component,
	destroy_component,
	detach,
	element,
	init,
	insert,
	mount_component,
	noop,
	safe_not_equal,
	space,
	transition_in,
	transition_out
} from "../../web_modules/svelte/internal.js";

import Header from "./common/Header.js";
import Footer from "./common/Footer.js";
import routes from "../utility/Router.js";
import Router from "../../web_modules/svelte-spa-router.js";

function create_fragment(ctx) {
	let header;
	let t0;
	let main;
	let router;
	let t1;
	let footer;
	let current;
	header = new Header({});
	router = new Router({ props: { routes } });
	footer = new Footer({});

	return {
		c() {
			create_component(header.$$.fragment);
			t0 = space();
			main = element("main");
			create_component(router.$$.fragment);
			t1 = space();
			create_component(footer.$$.fragment);
			attr(main, "class", "main svelte-1sc8921");
		},
		m(target, anchor) {
			mount_component(header, target, anchor);
			insert(target, t0, anchor);
			insert(target, main, anchor);
			mount_component(router, main, null);
			insert(target, t1, anchor);
			mount_component(footer, target, anchor);
			current = true;
		},
		p: noop,
		i(local) {
			if (current) return;
			transition_in(header.$$.fragment, local);
			transition_in(router.$$.fragment, local);
			transition_in(footer.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(header.$$.fragment, local);
			transition_out(router.$$.fragment, local);
			transition_out(footer.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(header, detaching);
			if (detaching) detach(t0);
			if (detaching) detach(main);
			destroy_component(router);
			if (detaching) detach(t1);
			destroy_component(footer, detaching);
		}
	};
}

class App extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default App;