# This workflow will do a clean installation of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy GithubPage

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest # 必要に応じて特定のバージョンを指定できます

            - name: Install dependencies
              run: bun install

            - name: Build project
              run: bun run build

            - name: deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build
                  cname: n06ar.me
