# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: create Docs Branch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      
    - name: Merge Docs
      uses: devmasx/merge-branch@v1.3.0
      with:
          type: now
          target_branch: docs
          github_token: ${{ github.token }}
